<?php
return array (
  'autogenerated-2-c81e728d9d' => 
  array (
    'base' => 'http://localhost/formation/autogenerated-2',
    'errorHandling' => 
    array (
    ),
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 2,
    'routes' => 
    array (
    ),
  ),
  'root' => 
  array (
    'base' => 'http://localhost/formation/',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'English',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'typo3Language' => 'default',
        'locale' => 'en_US.UTF-8',
        'iso-639-1' => 'en',
        'navigationTitle' => 'English',
        'hreflang' => 'en-us',
        'direction' => 'ltr',
        'flag' => 'us',
      ),
    ),
    'rootPageId' => 1,
    'websiteTitle' => '',
  ),
);
#